server:  
  port: ${PORT:9999}
    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/piomin/sample-spring-microservices-advanced/tree/config
          username: ${github.username}
          password: ${github.password}
          searchPaths: account