server:  
  port: ${PORT:9999}
    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/piomin/sample-config-repo.git
          force-pull: true
          username: ${github.username}
          password: ${github.password}

logging:
  level:
    org.springframework.cloud.config: DEBUG
    
management:
  security:
    enabled: false