server:  
  port: ${PORT:9999}
    
spring:
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/piomin/sample-spring-microservices-advanced/tree/config
          uri: file:///C:\Users\minkowp\Repo\config-repo
#          username: ${github.username}
#          password: ${github.password}
#          searchPaths: account

management:
  security:
    enabled: false